import 'mangayomi_js_generator.dart';

/// Emits a **Dart** source for RepoForge, in the same shape as a hand-written
/// Foxtensions extension (`class DefaultExtension extends MProvider`).
///
/// Why Dart and not the JS this replaces: `d4rt` is one interpreter on every
/// platform, whereas `flutter_js` is QuickJS on Android and JavaScriptCore on
/// iOS. Worse, the JS HTTP bridge returns a response whose `body` never reaches
/// the source — verified by running a generated JS source against the live site,
/// where the fetch reported no body at all and every selector therefore matched
/// nothing. That made *every* generated JS source non-functional on both
/// platforms. The Dart runtime is the one the app defaults to in
/// `lib/eval/lib.dart`, and it is what every working Foxtensions source uses.
///
/// All detection work is reused as-is: framework identification, the selector
/// catalog and endpoint discovery all come from [MangayomiJsGenerator]'s spec
/// parsing, so only the code-emission layer differs.
class MangayomiDartGenerator {
  /// The generated `.dart` source text, ready to run under d4rt.
  static String generateSource(Map<String, dynamic> ext) {
    final s = MangayomiJsGenerator.specView(ext);

    // Framework-specific bodies first — these carry the AJAX/JSON/extractor
    // flow the generic body can't infer from CSS alone (e.g. Madara loads
    // chapters via an admin-ajax POST). Checked before itemType so a Madara
    // *novel* still gets the Madara body (it also exposes getHtmlContent).
    final String body;
    if (s.framework == 'Madara') {
      body = _madaraBody;
    } else if (s.framework == 'MangaThemesia' || s.framework == 'MangaStream') {
      body = _mangaThemesiaBody;
    } else if (s.framework == 'MMRCMS') {
      body = _mmrcmsBody;
    } else if (s.framework == 'DooPlay') {
      body = _dooplayBody;
    } else if (s.framework == 'AnimeStream') {
      body = _animeStreamBody;
    } else if (s.framework == 'Zorotheme (Anime)' || s.framework == 'Zorotheme') {
      body = _zorothemeBody;
    } else if (s.framework == 'DopeFlix') {
      body = _dopeflixBody;
    } else if (s.framework == 'FlameComics') {
      body = _flameBody;
    } else if (s.framework == 'Asura API' || s.framework == 'Asura') {
      // Client-rendered site backed by a REST API (api.<host>/api/series).
      body = _asuraApiBody;
    } else if (s.framework == 'LightNovelWP') {
      // LightNovel-WP is MangaThemesia's engine for novels — the same browse /
      // chapter structure, with getHtmlContent for the text.
      body = _mangaThemesiaBody;
    } else if (s.itemType == 2) {
      body = _novelBody;
    } else if (s.itemType == 1) {
      body = _animeBody;
    } else {
      body = _mangaBody;
    }

    return _fill(_header + body, s);
  }

  /// Repo-relative path for the generated file, e.g. `manga/src/en/foo.dart`.
  static String pkgPath(Map<String, dynamic> ext) =>
      MangayomiJsGenerator.pkgPath(ext).replaceAll(RegExp(r'\.js$'), '.dart');

  static String _fill(String template, DartSpecView s) {
    final map = <String, String>{
      '__CLASS__': s.className,
      '__POPULAR_PATH__': _d(s.popularPath),
      '__LATEST_PATH__': _d(s.latestPath),
      '__SEARCH_PATH__': _d(s.searchPath),
      '__ITEM_SEL__': _d(s.item),
      '__TITLE_SEL__': _d(s.title),
      '__COVER_SEL__': _d(s.cover),
      '__COVER_ATTR__': _d(s.coverAttr),
      '__NEXT_SEL__': _d(s.nextPage),
      '__D_TITLE__': _d(s.detailTitle),
      '__D_COVER__': _d(s.detailCover),
      '__D_DESC__': _d(s.detailDesc),
      '__D_AUTHOR__': _d(s.detailAuthor),
      '__D_GENRE__': _d(s.detailGenre),
      '__CH_LIST__': _d(s.chapterList),
      '__CH_NAME__': _d(s.chapterName),
      '__PAGE_IMG__': _d(s.pageImages),
      '__PAGE_ATTR__': _d(s.pageImageAttr),
      '__EP_LIST__': _d(s.episodeList),
      '__NAME__': _d(s.name),
    };
    var out = template;
    map.forEach((k, v) => out = out.replaceAll(k, v));
    return out;
  }

  /// Escape for a Dart single-quoted string literal.
  static String _d(String s) =>
      s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$');

  // ── Shared preamble ──────────────────────────────────────────────────────
  static const String _header = r'''
// Generated by RepoForge. Runs on d4rt, the same runtime as hand-written
// Foxtensions sources.

import 'dart:convert';
import 'package:foxlations/bridge_lib.dart';

class __CLASS__ extends MProvider {
  __CLASS__({required this.source});

  MSource source;
  final Client client = Client();

  String get baseUrl => source.baseUrl;

  Map<String, String> _headers() => {'Referer': '$baseUrl/'};

  String _abs(String? url) {
    if (url == null || url.isEmpty) return '';
    if (url.startsWith('http')) return url;
    if (url.startsWith('//')) return 'https:$url';
    return '$baseUrl${url.startsWith('/') ? url : '/$url'}';
  }

  /// A role's selector is a comma-separated candidate list (the framework's own
  /// selectors first, then generic fallbacks). Try each in turn and keep the
  /// first that matches, so one source copes with a site changing its markup
  /// or serving a different layout on its search page than its browse page.
  List<MElement> _qa(dynamic node, String csv) {
    for (final s in csv.split(',')) {
      final t = s.trim();
      if (t.isEmpty) continue;
      try {
        final e = node.select(t);
        if (e != null && e.isNotEmpty) return e;
      } catch (_) {}
    }
    return <MElement>[];
  }

  MElement? _q1(dynamic node, String csv) {
    for (final s in csv.split(',')) {
      final t = s.trim();
      if (t.isEmpty) continue;
      try {
        final e = node.selectFirst(t);
        if (e != null) return e;
      } catch (_) {}
    }
    return null;
  }

  /// Covers are usually lazy-loaded and sites disagree on which attribute holds
  /// the real address, so try the common set and skip inline placeholders.
  String _img(MElement? el) {
    if (el == null) return '';
    for (final a in ['__COVER_ATTR__', 'data-src', 'data-lazy-src',
                     'data-original', 'data-url', 'data-image']) {
      if (a.isEmpty) continue;
      final v = el.attr(a);
      if (v != null && v.isNotEmpty && !v.startsWith('data:')) return _abs(v);
    }
    final ss = el.attr('srcset');
    if (ss != null && ss.isNotEmpty) {
      final first = ss.split(',').first.trim().split(' ').first;
      if (first.isNotEmpty && !first.startsWith('data:')) return _abs(first);
    }
    final s = el.getSrc();
    if (s != null && s.isNotEmpty && !s.startsWith('data:')) return _abs(s);
    return '';
  }

  /// Name, most reliable first: the title element's text, its title attribute
  /// (cover-only anchors carry the name there), then the cover's alt text.
  String _name(MElement item, MElement? titleEl, MElement? img) {
    var n = titleEl == null ? '' : titleEl.text.trim();
    if (n.isEmpty && titleEl != null) n = (titleEl.attr('title') ?? '').trim();
    if (n.isEmpty && img != null) n = (img.attr('alt') ?? '').trim();
    if (n.isEmpty) {
      final a = item.selectFirst('a');
      if (a != null) n = a.text.trim();
    }
    return n;
  }

  String _href(MElement item, MElement? titleEl) {
    final fromTitle = titleEl?.attr('href');
    if (fromTitle != null && fromTitle.isNotEmpty) return fromTitle;
    // The card may itself BE the anchor rather than contain one — common where
    // the whole tile is clickable. Looking only for a descendant <a> found
    // nothing and silently dropped every result.
    final own = item.attr('href');
    if (own != null && own.isNotEmpty) return own;
    return item.selectFirst('a')?.attr('href') ?? '';
  }
''';

  // ── Manga ────────────────────────────────────────────────────────────────
  static const String _mangaBody = r'''
  Future<MPages> _list(String pathTemplate, int page) async {
    final url = baseUrl + pathTemplate.replaceAll('{page}', '$page');
    final res = await client.get(url, headers: _headers());
    final doc = Document(res.body);
    final list = <MManga>[];

    for (final el in _qa(doc, '__ITEM_SEL__')) {
      final titleEl = _q1(el, '__TITLE_SEL__');
      final img = _q1(el, '__COVER_SEL__');
      final name = _name(el, titleEl, img);
      final href = _href(el, titleEl);
      // Require both. Ad slots dropped into a results grid match the card
      // selector but supply only one, which is how an advert gets listed.
      if (name.isEmpty || href.isEmpty) continue;
      final m = MManga();
      m.name = name;
      m.link = _abs(href);
      m.imageUrl = _img(img);
      list.add(m);
    }

    final hasNext = '__NEXT_SEL__'.isNotEmpty
        ? _q1(doc, '__NEXT_SEL__') != null
        : list.isNotEmpty;
    return MPages(list, hasNext);
  }

  @override
  Future<MPages> getPopular(int page) => _list('__POPULAR_PATH__', page);

  @override
  Future<MPages> getLatestUpdates(int page) => _list('__LATEST_PATH__', page);

  @override
  Future<MPages> search(String query, int page, FilterList filterList) {
    final p = '__SEARCH_PATH__'
        .replaceAll('{query}', Uri.encodeComponent(query));
    return _list(p, page);
  }

  /// OpenGraph is near-universal on content sites, so it fills the gaps when a
  /// bespoke site matches none of the detected selectors.
  String _meta(Document doc, List<String> props) {
    for (final p in props) {
      final el = doc.selectFirst("meta[property='" + p + "']") ??
          doc.selectFirst("meta[name='" + p + "']");
      final c = el?.attr('content');
      if (c != null && c.trim().isNotEmpty) return c.trim();
    }
    return '';
  }

  @override
  Future<MManga> getDetail(String url) async {
    final res = await client.get(_abs(url), headers: _headers());
    final doc = Document(res.body);
    final m = MManga();

    var name = _q1(doc, '__D_TITLE__')?.text.trim() ?? '';
    if (name.isEmpty) name = _meta(doc, ['og:title', 'twitter:title']);
    if (name.isEmpty) name = doc.selectFirst('h1')?.text.trim() ?? '';
    m.name = name;

    // Prefer og:image: the generic cover selector often grabs a site logo.
    var cover = _meta(doc, ['og:image', 'twitter:image']);
    if (cover.isEmpty) cover = _img(_q1(doc, '__D_COVER__'));
    m.imageUrl = _abs(cover);

    var desc = _q1(doc, '__D_DESC__')?.text.trim() ?? '';
    if (desc.isEmpty) desc = _meta(doc, ['og:description', 'description']);
    m.description = desc;

    final author = _q1(doc, '__D_AUTHOR__');
    if (author != null) m.author = author.text.trim();

    final genres = <String>[];
    for (final g in _qa(doc, '__D_GENRE__')) {
      final t = g.text.trim();
      if (t.isNotEmpty && t.length < 30 && !genres.contains(t)) genres.add(t);
    }
    if (genres.isNotEmpty) m.genre = genres;

    final chapters = <MChapter>[];
    for (final el in _qa(doc, '__CH_LIST__')) {
      final a = _q1(el, '__CH_NAME__') ?? el.selectFirst('a');
      if (a == null) continue;
      final href = a.attr('href') ?? el.attr('href') ?? '';
      if (href.isEmpty) continue;
      final c = MChapter();
      c.url = _abs(href);
      c.name = a.text.trim();
      chapters.add(c);
    }
    m.chapters = chapters;
    m.link = _abs(url);
    return m;
  }

  @override
  Future<List<dynamic>> getPageList(String url) async {
    final res = await client.get(_abs(url), headers: _headers());
    final doc = Document(res.body);
    final pages = <String>[];
    for (final img in _qa(doc, '__PAGE_IMG__')) {
      final v = img.attr('__PAGE_ATTR__') ?? img.getSrc();
      if (v != null && v.isNotEmpty && !v.startsWith('data:')) {
        pages.add(_abs(v));
      }
    }
    return pages;
  }

  @override
  List<dynamic> getFilterList() => [];

  @override
  List<dynamic> getSourcePreferences() => [];
}

__CLASS__ main(MSource source) {
  return __CLASS__(source: source);
}
''';

  // ── Asura-style REST API (api.<host>/api/series) ─────────────────────────
  // Sites like Asura Scans render their listings client-side from a JSON API,
  // so there is no HTML for the generic scraper to read. This body talks to
  // that API directly. The API host is derived from the site host (api.<host>),
  // and the endpoints mirror Asura's public shape:
  //   GET /api/series?sort=popular|latest&order=desc&offset=&limit=20
  //   GET /api/series?search=&...            (search)
  //   GET /api/series/<slug>                 (detail + metadata)
  //   GET /api/series/<slug>/chapters?...    (paginated chapter list)
  //   GET /api/series/<slug>/chapters/<ch>   (page images)
  static const String _asuraApiBody = r'''
  String get apiBase => 'https://api.' + Uri.parse(baseUrl).host;

  @override
  Future<MPages> getPopular(int page) async {
    final offset = (page - 1) * 20;
    final url = '$apiBase/api/series?sort=popular&order=desc&offset=$offset&limit=20';
    final res = await client.get(url, headers: _headers());
    return _parseSeriesList(res.body);
  }

  @override
  Future<MPages> getLatestUpdates(int page) async {
    final offset = (page - 1) * 20;
    final url = '$apiBase/api/series?sort=latest&order=desc&offset=$offset&limit=20';
    final res = await client.get(url, headers: _headers());
    return _parseSeriesList(res.body);
  }

  @override
  Future<MPages> search(String query, int page, FilterList filterList) async {
    final offset = (page - 1) * 20;
    final q = Uri.encodeComponent(query);
    final url = '$apiBase/api/series?search=$q&offset=$offset&limit=20&sort=rating&order=desc';
    final res = await client.get(url, headers: _headers());
    return _parseSeriesList(res.body);
  }

  @override
  Future<MManga> getDetail(String url) async {
    var path = url.replaceAll(baseUrl, '').replaceAll('/comics/', '');
    if (path.endsWith('/')) path = path.substring(0, path.length - 1);
    final slug = path.replaceAll(RegExp(r'-[a-f0-9]{8}$'), '');

    final apiUrl = '$apiBase/api/series/$slug';
    final res = await client.get(apiUrl, headers: _headers());
    final body = res.body;
    final manga = MManga();

    String seriesJson = body;
    final seriesStart = body.indexOf(',"series":{');
    if (seriesStart >= 0) {
      final afterSeries = body.substring(seriesStart);
      var endIdx = afterSeries.indexOf(',"recommended_series"');
      if (endIdx < 0) endIdx = afterSeries.indexOf(',"chapters"');
      if (endIdx < 0) endIdx = afterSeries.length;
      seriesJson = afterSeries.substring(0, endIdx);
    }

    final titleMatch = RegExp(r'"title"\s*:\s*"((?:[^"\\]|\\.)*)"').firstMatch(seriesJson);
    if (titleMatch != null) manga.name = titleMatch.group(1)!.replaceAll(r'\"', '"');
    final descMatch = RegExp(r'"description"\s*:\s*"((?:[^"\\]|\\.)*)"').firstMatch(seriesJson);
    if (descMatch != null) manga.description = descMatch.group(1)!.replaceAll(r'\n', '\n').replaceAll(r'\"', '"');
    final coverMatch = RegExp(r'"cover"\s*:\s*"([^"]*)"').firstMatch(seriesJson);
    if (coverMatch == null) {
      final coverUrlMatch = RegExp(r'"cover_url"\s*:\s*"([^"]*)"').firstMatch(seriesJson);
      if (coverUrlMatch != null) manga.imageUrl = coverUrlMatch.group(1);
    } else {
      manga.imageUrl = coverMatch.group(1);
    }
    final authorMatch = RegExp(r'"author"\s*:\s*"([^"]*)"').firstMatch(seriesJson);
    if (authorMatch != null) manga.author = authorMatch.group(1);
    final statusMatch = RegExp(r'"status"\s*:\s*"([^"]*)"').firstMatch(seriesJson);
    if (statusMatch != null) {
      final st = statusMatch.group(1)!.toLowerCase();
      if (st.contains('ongoing')) { manga.status = 0; }
      else if (st.contains('completed')) { manga.status = 1; }
      else if (st.contains('hiatus')) { manga.status = 2; }
    }
    final genresBlock = RegExp(r'"genres"\s*:\s*\[(.*?)\]', dotAll: true).firstMatch(seriesJson);
    if (genresBlock != null) {
      final names = RegExp(r'"name"\s*:\s*"([^"]*)"').allMatches(genresBlock.group(1)!);
      if (names.isNotEmpty) manga.genre = names.map((m) => m.group(1)!).toList();
    }

    final chapters = <MChapter>[];
    var offset = 0;
    var hasMore = true;
    while (hasMore) {
      final chUrl = '$apiBase/api/series/$slug/chapters?offset=$offset&limit=100';
      final chRes = await client.get(chUrl, headers: _headers());
      final chBody = chRes.body;
      var found = 0;
      final chEntries = chBody.split('"series_id":');
      for (final entry in chEntries.skip(1)) {
        final numMatch = RegExp(r'"number"\s*:\s*(\d+)').firstMatch(entry);
        final slugMatch = RegExp(r'"slug"\s*:\s*"([^"]*)"').firstMatch(entry);
        final dateMatch = RegExp(r'"published_at"\s*:\s*"([^"]*)"').firstMatch(entry);
        final chTitleMatch = RegExp(r'"title"\s*:\s*"((?:[^"\\]|\\.)*)"').firstMatch(entry);
        if (numMatch != null && slugMatch != null) {
          final ch = MChapter();
          final number = numMatch.group(1)!;
          final chSlug = slugMatch.group(1)!;
          final title = chTitleMatch?.group(1) ?? '';
          ch.name = title.isNotEmpty && title != 'null' ? 'Chapter $number: $title' : 'Chapter $number';
          ch.url = '$baseUrl/comics/$path/$chSlug';
          if (dateMatch != null) ch.dateUpload = dateMatch.group(1);
          chapters.add(ch);
          found++;
        }
      }
      hasMore = found >= 100;
      offset += 100;
    }
    manga.chapters = chapters;
    return manga;
  }

  @override
  Future<List<dynamic>> getPageList(String url) async {
    final path = url.replaceAll(baseUrl, '').replaceAll('/comics/', '');
    final parts = path.split('/');
    if (parts.length < 2) return [];
    final seriesSlug = parts[0].replaceAll(RegExp(r'-[a-f0-9]{8}$'), '');
    final chapterSlug = parts[1];
    final apiUrl = '$apiBase/api/series/$seriesSlug/chapters/$chapterSlug';
    final res = await client.get(apiUrl, headers: _headers());
    final body = res.body;
    final pages = <String>[];
    final urlPattern = RegExp(r'"(?:url|image_url|page_url|image|src)"\s*:\s*"([^"]*)"');
    for (final m in urlPattern.allMatches(body)) {
      final imgUrl = m.group(1)!.replaceAll(r'\/', '/');
      if (imgUrl.contains('.jpg') || imgUrl.contains('.png') || imgUrl.contains('.webp') || imgUrl.contains('.jpeg')) {
        pages.add(imgUrl);
      }
    }
    return pages;
  }

  @override
  List<dynamic> getFilterList() => [];

  @override
  List<dynamic> getSourcePreferences() => [];

  MPages _parseSeriesList(String body) {
    final mangaList = <MManga>[];
    final data = jsonDecode(body);
    final series = data['data'];
    if (series is List) {
      for (final s in series) {
        final manga = MManga();
        final title = s['series_title'] ?? s['name'] ?? s['title'] ?? 'Unknown';
        manga.name = title.toString();
        final pubUrl = (s['public_url'] ?? '').toString();
        manga.link = pubUrl.startsWith('http') ? pubUrl : '$baseUrl$pubUrl';
        manga.imageUrl = (s['cover'] ?? s['cover_url'] ?? '').toString();
        if (manga.name!.isNotEmpty) mangaList.add(manga);
      }
    }
    return MPages(mangaList, mangaList.length >= 20);
  }
}

__CLASS__ main(MSource source) {
  return __CLASS__(source: source);
}
''';

  // ── Light novel: chapters are text, not page images ──────────────────────
  static const String _novelBody = r'''
  Future<MPages> _list(String pathTemplate, int page) async {
    final url = baseUrl + pathTemplate.replaceAll('{page}', '$page');
    final res = await client.get(url, headers: _headers());
    final doc = Document(res.body);
    final list = <MManga>[];

    for (final el in _qa(doc, '__ITEM_SEL__')) {
      final titleEl = _q1(el, '__TITLE_SEL__');
      final img = _q1(el, '__COVER_SEL__');
      final name = _name(el, titleEl, img);
      final href = _href(el, titleEl);
      if (name.isEmpty || href.isEmpty) continue;
      final m = MManga();
      m.name = name;
      m.link = _abs(href);
      m.imageUrl = _img(img);
      list.add(m);
    }

    final hasNext = '__NEXT_SEL__'.isNotEmpty
        ? _q1(doc, '__NEXT_SEL__') != null
        : list.isNotEmpty;
    return MPages(list, hasNext);
  }

  @override
  Future<MPages> getPopular(int page) => _list('__POPULAR_PATH__', page);

  @override
  Future<MPages> getLatestUpdates(int page) => _list('__LATEST_PATH__', page);

  @override
  Future<MPages> search(String query, int page, FilterList filterList) {
    final p = '__SEARCH_PATH__'
        .replaceAll('{query}', Uri.encodeComponent(query));
    return _list(p, page);
  }

  @override
  Future<MManga> getDetail(String url) async {
    final res = await client.get(_abs(url), headers: _headers());
    final doc = Document(res.body);
    final m = MManga();

    var name = _q1(doc, '__D_TITLE__')?.text.trim() ?? '';
    if (name.isEmpty) name = doc.selectFirst('h1')?.text.trim() ?? '';
    m.name = name;

    final coverEl = _q1(doc, '__D_COVER__');
    if (coverEl != null) m.imageUrl = _img(coverEl);

    final desc = _q1(doc, '__D_DESC__');
    if (desc != null) m.description = desc.text.trim();

    final author = _q1(doc, '__D_AUTHOR__');
    if (author != null) m.author = author.text.trim();

    final chapters = <MChapter>[];
    for (final el in _qa(doc, '__CH_LIST__')) {
      final a = _q1(el, '__CH_NAME__') ?? el.selectFirst('a');
      if (a == null) continue;
      final href = a.attr('href') ?? el.attr('href') ?? '';
      if (href.isEmpty) continue;
      final c = MChapter();
      c.url = _abs(href);
      c.name = a.text.trim();
      chapters.add(c);
    }
    m.chapters = chapters;
    m.link = _abs(url);
    return m;
  }

  /// Novels deliver the chapter body as HTML text rather than page images.
  @override
  Future<String> getHtmlContent(String url) async {
    final res = await client.get(_abs(url), headers: _headers());
    final doc = Document(res.body);
    final el = _q1(doc, '__PAGE_IMG__');
    return el == null ? '' : el.innerHtml;
  }

  @override
  List<dynamic> getFilterList() => [];

  @override
  List<dynamic> getSourcePreferences() => [];
}

__CLASS__ main(MSource source) {
  return __CLASS__(source: source);
}
''';

  // ── Anime: episodes instead of chapters ──────────────────────────────────
  static const String _animeBody = r'''
  Future<MPages> _list(String pathTemplate, int page) async {
    final url = baseUrl + pathTemplate.replaceAll('{page}', '$page');
    final res = await client.get(url, headers: _headers());
    final doc = Document(res.body);
    final list = <MManga>[];

    for (final el in _qa(doc, '__ITEM_SEL__')) {
      final titleEl = _q1(el, '__TITLE_SEL__');
      final img = _q1(el, '__COVER_SEL__');
      final name = _name(el, titleEl, img);
      final href = _href(el, titleEl);
      if (name.isEmpty || href.isEmpty) continue;
      final m = MManga();
      m.name = name;
      m.link = _abs(href);
      m.imageUrl = _img(img);
      list.add(m);
    }

    final hasNext = '__NEXT_SEL__'.isNotEmpty
        ? _q1(doc, '__NEXT_SEL__') != null
        : list.isNotEmpty;
    return MPages(list, hasNext);
  }

  @override
  Future<MPages> getPopular(int page) => _list('__POPULAR_PATH__', page);

  @override
  Future<MPages> getLatestUpdates(int page) => _list('__LATEST_PATH__', page);

  @override
  Future<MPages> search(String query, int page, FilterList filterList) {
    final p = '__SEARCH_PATH__'
        .replaceAll('{query}', Uri.encodeComponent(query));
    return _list(p, page);
  }

  @override
  Future<MManga> getDetail(String url) async {
    final res = await client.get(_abs(url), headers: _headers());
    final doc = Document(res.body);
    final m = MManga();

    var name = _q1(doc, '__D_TITLE__')?.text.trim() ?? '';
    if (name.isEmpty) name = doc.selectFirst('h1')?.text.trim() ?? '';
    m.name = name;

    final coverEl = _q1(doc, '__D_COVER__');
    if (coverEl != null) m.imageUrl = _img(coverEl);

    final desc = _q1(doc, '__D_DESC__');
    if (desc != null) m.description = desc.text.trim();

    final episodes = <MChapter>[];
    for (final el in _qa(doc, '__EP_LIST__')) {
      final a = el.selectFirst('a') ?? el;
      final href = a.attr('href') ?? '';
      if (href.isEmpty) continue;
      final c = MChapter();
      c.url = _abs(href);
      c.name = a.text.trim();
      episodes.add(c);
    }
    m.chapters = episodes;
    m.link = _abs(url);
    return m;
  }

  /// Episode pages nearly always delegate playback to a third-party host in an
  /// iframe, and each host needs its own extractor. Generation can't know which
  /// one a site uses, so the embed is surfaced as-is rather than guessed at.
  @override
  Future<List<MVideo>> getVideoList(String url) async {
    final res = await client.get(_abs(url), headers: _headers());
    final doc = Document(res.body);
    final videos = <MVideo>[];
    for (final f in doc.select('iframe')) {
      final src = f.attr('src');
      if (src == null || src.isEmpty || src.startsWith('javascript')) continue;
      final v = MVideo();
      v.url = _abs(src);
      v.originalUrl = _abs(src);
      v.quality = 'Embed';
      v.headers = {'Referer': '$baseUrl/'};
      videos.add(v);
    }
    return videos;
  }

  @override
  List<dynamic> getFilterList() => [];

  @override
  List<dynamic> getSourcePreferences() => [];
}

__CLASS__ main(MSource source) {
  return __CLASS__(source: source);
}
''';

  // ── Madara (WordPress) ────────────────────────────────────────────────────
  // Ported from the JS Madara body. The part the generic body lacks: chapters
  // arrive via an admin-ajax POST (or /ajax/chapters), and reader pages via
  // ?style=list. Serves manga AND novel Madara sites (getHtmlContent included).
  static const String _madaraBody = r'''
  Future<MPages> _mList(String body) async {
    final doc = Document(body);
    final list = <MManga>[];
    final seen = <String>{};
    for (final el in _qa(doc, '__ITEM_SEL__')) {
      final a = _q1(el, 'div.post-title a, h3.h5 a, h3 a') ?? el.selectFirst('a');
      if (a == null) continue;
      final link = _abs(a.attr('href'));
      if (link.isEmpty || seen.contains(link)) continue;
      seen.add(link);
      final m = MManga();
      m.name = a.text.trim();
      m.link = link;
      m.imageUrl = _img(el.selectFirst('img'));
      list.add(m);
    }
    return MPages(list, list.isNotEmpty);
  }

  @override
  Future<MPages> getPopular(int page) async {
    final res = await client.get(
        baseUrl + '__POPULAR_PATH__'.replaceAll('{page}', '$page'),
        headers: _headers());
    return _mList(res.body);
  }

  @override
  Future<MPages> getLatestUpdates(int page) async {
    final res = await client.get(
        baseUrl + '__LATEST_PATH__'.replaceAll('{page}', '$page'),
        headers: _headers());
    return _mList(res.body);
  }

  @override
  Future<MPages> search(String query, int page, FilterList filterList) async {
    final res = await client.get(
        '$baseUrl/page/$page/?s=${Uri.encodeComponent(query)}&post_type=wp-manga',
        headers: _headers());
    return _mList(res.body);
  }

  @override
  Future<MManga> getDetail(String url) async {
    final res = await client.get(_abs(url), headers: _headers());
    final doc = Document(res.body);
    final m = MManga();
    m.name = _q1(doc, 'div.post-title h1, div.post-title h3, h1')?.text.trim() ?? '';
    m.imageUrl = _img(_q1(doc, 'div.summary_image img'));
    m.description = _q1(doc, 'div.summary__content, div.description-summary, div.manga-excerpt, div.summary_content')?.text.trim() ?? '';
    final author = _q1(doc, 'div.author-content a');
    if (author != null) m.author = author.text.trim();
    final genre = <String>[];
    for (final g in _qa(doc, 'div.genres-content a')) {
      final t = g.text.trim();
      if (t.isNotEmpty) genre.add(t);
    }
    if (genre.isNotEmpty) m.genre = genre;
    var chapters = _mChapters(doc);
    if (chapters.isEmpty) chapters = await _mAjaxChapters(url, doc);
    m.chapters = chapters;
    m.link = _abs(url);
    return m;
  }

  List<MChapter> _mChapters(dynamic doc) {
    final out = <MChapter>[];
    for (final el in _qa(doc, 'li.wp-manga-chapter')) {
      final a = el.selectFirst('a');
      if (a == null) continue;
      final c = MChapter();
      c.name = a.text.trim();
      c.url = _abs(a.attr('href'));
      out.add(c);
    }
    return out;
  }

  Future<List<MChapter>> _mAjaxChapters(String url, dynamic doc) async {
    var body = '';
    final holder = doc.selectFirst("div[id^='manga-chapters-holder']");
    final mangaId = holder == null ? '' : (holder.attr('data-id') ?? '');
    final hdr = {
      'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
      'X-Requested-With': 'XMLHttpRequest',
      'Referer': '$baseUrl/',
    };
    if (mangaId.isNotEmpty) {
      try {
        final res = await client.post('$baseUrl/wp-admin/admin-ajax.php',
            headers: hdr, body: 'action=manga_get_chapters&manga=$mangaId');
        body = res.body;
      } catch (_) {}
    }
    if (!body.contains('wp-manga-chapter')) {
      try {
        var u = _abs(url);
        while (u.endsWith('/')) {
          u = u.substring(0, u.length - 1);
        }
        final res2 = await client.post('$u/ajax/chapters', headers: hdr, body: '');
        body = res2.body;
      } catch (_) {}
    }
    final out = <MChapter>[];
    if (body.isNotEmpty) {
      final cdoc = Document(body);
      for (final el in _qa(cdoc, 'li.wp-manga-chapter')) {
        final a = el.selectFirst('a');
        if (a == null) continue;
        final c = MChapter();
        c.name = a.text.trim();
        c.url = _abs(a.attr('href'));
        out.add(c);
      }
    }
    return out;
  }

  @override
  Future<List<dynamic>> getPageList(String url) async {
    var u = _abs(url).replaceAll('?style=paged', '');
    final sep = u.contains('?') ? '&' : '?';
    final res = await client.get('$u${sep}style=list', headers: _headers());
    final doc = Document(res.body);
    final pages = <String>[];
    for (final img in _qa(doc, 'div.page-break img, li.blocks-gallery-item img, div.reading-content img')) {
      final src = (img.attr('data-src') ?? img.attr('data-lazy-src') ?? img.getSrc() ?? '').trim();
      if (src.isNotEmpty && !src.startsWith('data:')) pages.add(_abs(src));
    }
    return pages;
  }

  @override
  Future<String> getHtmlContent(String url) async {
    final res = await client.get(_abs(url), headers: _headers());
    final doc = Document(res.body);
    final el = _q1(doc, 'div.reading-content, div.text-left, div.text-right, div.entry-content, .chapter-content, #chapter-content');
    return el == null ? '' : el.innerHtml;
  }

  @override
  List<dynamic> getFilterList() => [];

  @override
  List<dynamic> getSourcePreferences() => [];
}

__CLASS__ main(MSource source) {
  return __CLASS__(source: source);
}
''';

  // ── FlameComics (Next.js _next/data JSON) ─────────────────────────────────
  // Everything is JSON under /_next/data/{buildId}/… ; images live on a cdn.
  // host. Ported from the JS API body.
  static const String _flameBody = r'''
  String _cachedBid = '';

  Future<String> _bid() async {
    if (_cachedBid.isNotEmpty) return _cachedBid;
    final res = await client.get(baseUrl, headers: _headers());
    final m = RegExp(r'"buildId":"([^"]+)"').firstMatch(res.body);
    _cachedBid = m == null ? '' : (m.group(1) ?? '');
    return _cachedBid;
  }

  String get _cdn {
    var base = baseUrl;
    while (base.endsWith('/')) {
      base = base.substring(0, base.length - 1);
    }
    final mm = RegExp(r'^(https?://)(?:www\.)?(.+)$').firstMatch(base);
    return mm == null ? base : '${mm.group(1)}cdn.${mm.group(2)}';
  }

  Future<Map> _data(String path) async {
    final bid = await _bid();
    final res = await client.get('$baseUrl/_next/data/$bid/$path', headers: _headers());
    try {
      final d = jsonDecode(res.body);
      return d is Map ? d : {};
    } catch (_) {
      return {};
    }
  }

  MPages _seriesList(Map pp) {
    final arr = pp['series'] ?? pp['latestEntries'] ?? pp['popularEntries'] ??
        pp['entries'] ?? pp['data'] ?? [];
    final list = <MManga>[];
    if (arr is List) {
      for (final s in arr) {
        if (s is! Map || s['title'] == null) continue;
        final id = s['series_id'];
        final m = MManga();
        m.name = s['title'].toString();
        m.link = '$baseUrl/series/$id';
        m.imageUrl = s['cover'] != null
            ? '$_cdn/uploads/images/series/$id/${s['cover']}'
            : '';
        list.add(m);
      }
    }
    return MPages(list, list.length >= 20);
  }

  @override
  Future<MPages> getPopular(int page) async {
    final d = await _data('browse.json?page=$page');
    return _seriesList((d['pageProps'] as Map?) ?? {});
  }

  @override
  Future<MPages> getLatestUpdates(int page) async {
    final d = await _data('index.json');
    return _seriesList((d['pageProps'] as Map?) ?? {});
  }

  @override
  Future<MPages> search(String query, int page, FilterList filterList) async {
    final d = await _data('browse.json?search=${Uri.encodeComponent(query)}&page=$page');
    return _seriesList((d['pageProps'] as Map?) ?? {});
  }

  @override
  Future<MManga> getDetail(String url) async {
    var u = url;
    while (u.endsWith('/')) {
      u = u.substring(0, u.length - 1);
    }
    final id = u.split('/').last;
    final d = await _data('series/$id.json');
    final pp = (d['pageProps'] as Map?) ?? {};
    final s = (pp['series'] as Map?) ?? {};
    final m = MManga();
    m.name = (s['title'] ?? '').toString();
    m.imageUrl = s['cover'] != null
        ? '$_cdn/uploads/images/series/$id/${s['cover']}'
        : '';
    m.description = (s['description'] ?? '').toString();
    m.author = (s['author'] ?? '').toString();
    final genre = <String>[];
    final cats = s['categories'];
    if (cats is List) {
      for (final c in cats) {
        genre.add((c is Map ? (c['name'] ?? c) : c).toString());
      }
    }
    if (genre.isNotEmpty) m.genre = genre;
    final chapters = <MChapter>[];
    final chs = pp['chapters'];
    if (chs is List) {
      for (final c in chs) {
        if (c is! Map) continue;
        final title = (c['title'] != null && c['title'].toString() != 'null')
            ? ': ${c['title']}'
            : '';
        final ch = MChapter();
        ch.name = 'Chapter ${c['chapter']}$title';
        ch.url = '$baseUrl/series/$id/${c['token']}';
        chapters.add(ch);
      }
    }
    m.chapters = chapters;
    m.link = url;
    return m;
  }

  @override
  Future<List<dynamic>> getPageList(String url) async {
    var u = url;
    while (u.endsWith('/')) {
      u = u.substring(0, u.length - 1);
    }
    final parts = u.split('/');
    final token = parts.removeLast();
    final sid = parts.removeLast();
    final d = await _data('series/$sid/$token.json');
    final pp = (d['pageProps'] as Map?) ?? {};
    final ch = (pp['chapter'] as Map?) ?? {};
    final imgs = (ch['images'] as Map?) ?? {};
    final cid = ch['series_id'] ?? sid;
    final ctok = ch['token'] ?? token;
    final keys = imgs.keys.toList()
      ..sort((a, b) => (int.tryParse('$a') ?? 0) - (int.tryParse('$b') ?? 0));
    final pages = <String>[];
    for (final k in keys) {
      final im = imgs[k];
      final name = (im is Map ? im['name'] : im)?.toString() ?? '';
      if (name.isNotEmpty) {
        pages.add('$_cdn/uploads/images/series/$cid/$ctok/$name');
      }
    }
    return pages;
  }

  @override
  List<dynamic> getFilterList() => [];

  @override
  List<dynamic> getSourcePreferences() => [];
}

__CLASS__ main(MSource source) {
  return __CLASS__(source: source);
}
''';

  // ── DooPlay (WordPress anime/donghua/drama/movie theme) ───────────────────
  // Episodes from ul.episodios; playback via the doo_player_ajax POST that
  // returns an embed URL, then dispatched to the built-in host extractors.
  // Base DooPlay leaves video per-site, so this is a best-effort generic flow.
  static const String _dooplayBody = r'''
  Future<List<MVideo>> _extract(String url) async {
    final u = url.toLowerCase();
    try {
      if (u.contains('dood') || u.contains('d0000d') || u.contains('ds2play') || u.contains('dooood')) return await doodExtractor(url, 'Doodstream');
      if (u.contains('streamwish') || u.contains('embedwish') || u.contains('mwish') || u.contains('vidhide') || u.contains('streamhide') || u.contains('filelions') || u.contains('kswplayer')) return await streamWishExtractor(url, 'StreamWish');
      if (u.contains('filemoon') || u.contains('moonplayer')) return await filemoonExtractor(url, '', '');
      if (u.contains('voe')) return await voeExtractor(url, 'Voe');
      if (u.contains('streamtape')) return await streamTapeExtractor(url, 'StreamTape');
      if (u.contains('mp4upload')) return await mp4UploadExtractor(url, null, '', '');
      if (u.contains('sibnet')) return await sibnetExtractor(url, '');
      if (u.contains('vidbom') || u.contains('vidbem') || u.contains('vidshare')) return await vidBomExtractor(url);
      if (u.contains('ok.ru') || u.contains('odnoklassniki')) return await okruExtractor(url);
      if (u.contains('yourupload')) return await yourUploadExtractor(url, null, 'YourUpload', '');
      if (u.contains('sendvid')) return await sendVidExtractor(url, null, '');
      if (u.contains('streamlare') || u.contains('slmaxed')) return await streamlareExtractor(url, '', '');
    } catch (_) {}
    return <MVideo>[];
  }

  String _iframeSrc(String html) {
    final f = Document(html).selectFirst('iframe');
    return f == null ? '' : (f.attr('src') ?? '');
  }

  Future<MPages> _dList(String path, int page) async {
    final res = await client.get(
        baseUrl + path.replaceAll('{page}', '$page'), headers: _headers());
    final doc = Document(res.body);
    final list = <MManga>[];
    final seen = <String>{};
    for (final el in _qa(doc, 'div.items article, .result-item article, article.item')) {
      final a = _q1(el, 'div.poster a, div.data h3 a, a');
      if (a == null) continue;
      final href = a.attr('href') ?? '';
      if (href.isEmpty || seen.contains(href)) continue;
      seen.add(href);
      final img = _q1(el, 'div.poster img, img');
      var name = _q1(el, 'div.data h3')?.text.trim() ?? '';
      if (name.isEmpty) name = ((img?.attr('alt')) ?? a.text).trim();
      if (name.isEmpty) continue;
      final m = MManga();
      m.name = name;
      m.link = _abs(href);
      m.imageUrl = _img(img);
      list.add(m);
    }
    return MPages(list, list.isNotEmpty);
  }

  @override
  Future<MPages> getPopular(int page) => _dList('__POPULAR_PATH__', page);

  @override
  Future<MPages> getLatestUpdates(int page) => _dList('__LATEST_PATH__', page);

  @override
  Future<MPages> search(String query, int page, FilterList filterList) async {
    final res = await client.get(
        '$baseUrl/?s=${Uri.encodeComponent(query)}', headers: _headers());
    final doc = Document(res.body);
    final list = <MManga>[];
    for (final el in _qa(doc, 'div.result-item article, div.items article')) {
      final a = _q1(el, 'div.thumbnail a, div.poster a, div.details .title a, a');
      if (a == null) continue;
      final href = a.attr('href') ?? '';
      if (href.isEmpty) continue;
      final img = _q1(el, 'img');
      var name = _q1(el, 'div.title a, div.data h3')?.text.trim() ?? '';
      if (name.isEmpty) name = ((img?.attr('alt')) ?? a.text).trim();
      if (name.isEmpty) continue;
      final m = MManga();
      m.name = name;
      m.link = _abs(href);
      m.imageUrl = _img(img);
      list.add(m);
    }
    return MPages(list, false);
  }

  @override
  Future<MManga> getDetail(String url) async {
    final res = await client.get(_abs(url), headers: _headers());
    final doc = Document(res.body);
    final m = MManga();
    m.name = _q1(doc, 'div.data h1, div.sheader .data h1, h1.entry-title')?.text.trim() ?? '';
    m.imageUrl = _img(_q1(doc, 'div.poster img, div.sheader .poster img'));
    m.description = _q1(doc, 'div.wp-content p, #info .wp-content, div.contenido p')?.text.trim() ?? '';
    final genre = <String>[];
    for (final g in _qa(doc, 'div.sgeneros a, .genres a')) {
      final t = g.text.trim();
      if (t.isNotEmpty) genre.add(t);
    }
    if (genre.isNotEmpty) m.genre = genre;
    final episodes = <MChapter>[];
    for (final li in _qa(doc, 'ul.episodios > li, ul.episodios li')) {
      final a = li.selectFirst('a');
      if (a == null) continue;
      final href = a.attr('href') ?? '';
      if (href.isEmpty) continue;
      final numer = _q1(li, 'div.numerando')?.text.trim() ?? '';
      final t = _q1(li, 'div.episodiotitle a')?.text.trim() ?? a.text.trim();
      final c = MChapter();
      c.name = numer.isNotEmpty ? '$numer - $t' : t;
      c.url = _abs(href);
      episodes.add(c);
    }
    if (episodes.isEmpty) {
      final c = MChapter();
      c.name = 'Movie';
      c.url = _abs(url);
      episodes.add(c);
    }
    m.chapters = episodes;
    m.link = _abs(url);
    return m;
  }

  @override
  Future<List<MVideo>> getVideoList(String url) async {
    final res = await client.get(_abs(url), headers: _headers());
    final doc = Document(res.body);
    final videos = <MVideo>[];
    for (final opt in doc.select('ul#playeroptionsul li.dooplay_player_option')) {
      final post = opt.attr('data-post') ?? '';
      final nume = opt.attr('data-nume') ?? '';
      final type = opt.attr('data-type') ?? '';
      if (post.isEmpty) continue;
      try {
        final ajax = await client.post('$baseUrl/wp-admin/admin-ajax.php',
            headers: {'X-Requested-With': 'XMLHttpRequest', 'Referer': '$baseUrl/'},
            body: 'action=doo_player_ajax&post=$post&nume=$nume&type=$type');
        final data = jsonDecode(ajax.body);
        var embed = (data is Map ? data['embed_url'] : null)?.toString() ?? '';
        if (embed.contains('<iframe') || embed.contains('src=')) {
          final s = _iframeSrc(embed);
          if (s.isNotEmpty) embed = s;
        }
        if (embed.isEmpty) continue;
        videos.addAll(await _extract(_abs(embed)));
      } catch (_) {}
    }
    if (videos.isEmpty) {
      for (final f in doc.select('iframe')) {
        final src = f.attr('src') ?? '';
        if (src.isNotEmpty && !src.startsWith('javascript')) {
          videos.addAll(await _extract(_abs(src)));
        }
      }
    }
    return videos;
  }

  @override
  List<dynamic> getFilterList() => [];

  @override
  List<dynamic> getSourcePreferences() => [];
}

__CLASS__ main(MSource source) {
  return __CLASS__(source: source);
}
''';

  // ── DopeFlix / FlixHQ (movies + TV + anime) ───────────────────────────────
  // Movies: /ajax/episode/list/{id}. TV: /ajax/season/list → season/episodes →
  // episode/servers. Each server's /ajax/episode/sources/{id} yields a rapidcloud
  // embed, resolved by megaCloudExtractor (same rabbit system as MegaCloud).
  static const String _dopeflixBody = r'''
  Map<String, String> _ajaxHeaders(String referer) => {
        'X-Requested-With': 'XMLHttpRequest',
        'Referer': referer,
        'Accept': '*/*',
      };

  String _idOf(String url) {
    var u = url.split('?').first;
    while (u.endsWith('/')) {
      u = u.substring(0, u.length - 1);
    }
    final last = u.split('/').last;
    return last.contains('-') ? last.split('-').last : last;
  }

  String _ajaxHtml(String body) {
    try {
      final j = jsonDecode(body);
      if (j is Map && j['html'] != null) return j['html'].toString();
    } catch (_) {}
    return body;
  }

  MPages _fParse(String body) {
    final doc = Document(body);
    final list = <MManga>[];
    for (final el in _qa(doc, 'div.flw-item')) {
      final a = _q1(el, 'div.film-detail a, .film-name a, h3.film-name a');
      final poster = _q1(el, 'div.film-poster img, img.film-poster-img');
      final href = (a?.attr('href')) ?? el.selectFirst('a')?.attr('href') ?? '';
      if (href.isEmpty) continue;
      var name = ((a?.attr('title')) ?? (a?.text) ?? '').trim();
      if (name.isEmpty && poster != null) name = (poster.attr('alt') ?? '').trim();
      if (name.isEmpty) continue;
      final m = MManga();
      m.name = name;
      m.link = _abs(href);
      m.imageUrl = poster == null
          ? ''
          : _abs((poster.attr('data-src')) ?? poster.getSrc() ?? '');
      list.add(m);
    }
    final hasNext = _q1(doc, 'li.page-item a[title=Next], ul.pagination li.active + li') != null;
    return MPages(list, hasNext);
  }

  @override
  Future<MPages> getPopular(int page) async {
    final res = await client.get(
        baseUrl + '__POPULAR_PATH__'.replaceAll('{page}', '$page'),
        headers: _headers());
    return _fParse(res.body);
  }

  @override
  Future<MPages> getLatestUpdates(int page) async {
    final res = await client.get(
        baseUrl + '__LATEST_PATH__'.replaceAll('{page}', '$page'),
        headers: _headers());
    return _fParse(res.body);
  }

  @override
  Future<MPages> search(String query, int page, FilterList filterList) async {
    final res = await client.get(
        '$baseUrl/search/${Uri.encodeComponent(query).replaceAll('%20', '-')}',
        headers: _headers());
    return _fParse(res.body);
  }

  @override
  Future<MManga> getDetail(String url) async {
    final res = await client.get(_abs(url), headers: _headers());
    final doc = Document(res.body);
    final m = MManga();
    m.name = _q1(doc, 'div.detail_page-infor h2.heading-name, h2.film-name, .heading-name')?.text.trim() ?? '';
    m.imageUrl = _abs(_q1(doc, 'div.film-poster img, .detail_page-infor img')?.attr('src') ?? '');
    m.description = _q1(doc, 'div.description, .detail_page-watch .description')?.text.trim() ?? '';
    final id = _idOf(url);
    final isMovie = _abs(url).contains('/movie/');
    final episodes = <MChapter>[];
    try {
      if (isMovie) {
        final c = MChapter();
        c.name = 'Movie';
        c.url = '$baseUrl/ajax/episode/list/$id';
        episodes.add(c);
      } else {
        final seasonRes = await client.get('$baseUrl/ajax/season/list/$id',
            headers: _ajaxHeaders(_abs(url)));
        final sdoc = Document(_ajaxHtml(seasonRes.body));
        var sIdx = 0;
        for (final season in sdoc.select('a.dropdown-item, .ss-item, div.dropdown-menu a')) {
          final seasonId = season.attr('data-id') ?? '';
          if (seasonId.isEmpty) continue;
          sIdx++;
          try {
            final epRes = await client.get('$baseUrl/ajax/season/episodes/$seasonId',
                headers: _ajaxHeaders(_abs(url)));
            final edoc = Document(_ajaxHtml(epRes.body));
            for (final ep in edoc.select('.eps-item, a.eps-item')) {
              final epId = ep.attr('data-id') ?? '';
              if (epId.isEmpty) continue;
              final t = ((ep.attr('title')) ?? ep.text).trim();
              final c = MChapter();
              c.name = 'S$sIdx $t';
              c.url = '$baseUrl/ajax/episode/servers/$epId';
              episodes.add(c);
            }
          } catch (_) {}
        }
      }
    } catch (_) {}
    m.chapters = episodes;
    m.link = _abs(url);
    return m;
  }

  @override
  Future<List<MVideo>> getVideoList(String url) async {
    final videos = <MVideo>[];
    try {
      final serversRes = await client.get(_abs(url), headers: _ajaxHeaders('$baseUrl/'));
      final sdoc = Document(_ajaxHtml(serversRes.body));
      for (final srv in sdoc.select('a.link-item, .server-item, ul.fss-list a, a[data-linkid], a[data-id]')) {
        var linkId = srv.attr('data-linkid') ?? '';
        if (linkId.isEmpty) linkId = srv.attr('data-id') ?? '';
        if (linkId.isEmpty) continue;
        final name = srv.text.trim();
        try {
          final srcRes = await client.get('$baseUrl/ajax/episode/sources/$linkId',
              headers: _ajaxHeaders('$baseUrl/'));
          final src = jsonDecode(srcRes.body);
          final link = (src is Map ? src['link'] : null)?.toString() ?? '';
          if (link.isEmpty) continue;
          videos.addAll(await megaCloudExtractor(link, name.isEmpty ? 'FlixHQ' : name));
        } catch (_) {}
      }
    } catch (_) {}
    return videos;
  }

  @override
  List<dynamic> getFilterList() => [];

  @override
  List<dynamic> getSourcePreferences() => [];
}

__CLASS__ main(MSource source) {
  return __CLASS__(source: source);
}
''';

  // ── Zorotheme (HiAnime / aniwatch family) ─────────────────────────────────
  // Episodes and servers come from /ajax/v2/episode/{list,servers,sources};
  // the server "link" is a MegaCloud embed, resolved by megaCloudExtractor.
  static const String _zorothemeBody = r'''
  Map<String, String> _ajaxHeaders(String referer) => {
        'X-Requested-With': 'XMLHttpRequest',
        'Referer': referer,
        'Accept': '*/*',
      };

  String _idOf(String url) {
    var u = url.split('?').first;
    while (u.endsWith('/')) {
      u = u.substring(0, u.length - 1);
    }
    final last = u.split('/').last;
    return last.contains('-') ? last.split('-').last : last;
  }

  MPages _zParse(String body) {
    final doc = Document(body);
    final list = <MManga>[];
    for (final el in _qa(doc, 'div.flw-item')) {
      final a = _q1(el, 'div.film-detail a.dynamic-name, .film-name a, h3.film-name a');
      final poster = _q1(el, 'div.film-poster > img, img.film-poster-img');
      final href = (a?.attr('href')) ?? el.selectFirst('a')?.attr('href') ?? '';
      if (href.isEmpty) continue;
      var name = ((a?.attr('title')) ?? (a?.text) ?? '').trim();
      if (name.isEmpty && poster != null) name = (poster.attr('alt') ?? '').trim();
      if (name.isEmpty) continue;
      final m = MManga();
      m.name = name;
      m.link = _abs(href);
      m.imageUrl = poster == null
          ? ''
          : _abs((poster.attr('data-src')) ?? poster.getSrc() ?? '');
      list.add(m);
    }
    final hasNext = _q1(doc, 'li.page-item a[title=Next], ul.pagination li.active + li') != null;
    return MPages(list, hasNext);
  }

  @override
  Future<MPages> getPopular(int page) async {
    final res = await client.get(
        baseUrl + '__POPULAR_PATH__'.replaceAll('{page}', '$page'),
        headers: _headers());
    return _zParse(res.body);
  }

  @override
  Future<MPages> getLatestUpdates(int page) async {
    final res = await client.get(
        baseUrl + '__LATEST_PATH__'.replaceAll('{page}', '$page'),
        headers: _headers());
    return _zParse(res.body);
  }

  @override
  Future<MPages> search(String query, int page, FilterList filterList) async {
    final res = await client.get(
        '$baseUrl/search?keyword=${Uri.encodeComponent(query)}&page=$page',
        headers: _headers());
    return _zParse(res.body);
  }

  @override
  Future<MManga> getDetail(String url) async {
    final res = await client.get(_abs(url), headers: _headers());
    final doc = Document(res.body);
    final m = MManga();
    m.name = _q1(doc, 'h2.film-name, .anisc-detail h2.film-name, h1.film-name')?.text.trim() ?? '';
    m.imageUrl = _abs(_q1(doc, 'div.film-poster img, .anisc-poster img')?.attr('src') ?? '');
    m.description = _q1(doc, 'div.film-description .text, div.film-description')?.text.trim() ?? '';
    final genre = <String>[];
    for (final g in _qa(doc, "div.item-list a[href*='genre'], div.genres a")) {
      final t = g.text.trim();
      if (t.isNotEmpty) genre.add(t);
    }
    if (genre.isNotEmpty) m.genre = genre;
    final animeId = _idOf(url);
    final episodes = <MChapter>[];
    try {
      final ep = await client.get('$baseUrl/ajax/v2/episode/list/$animeId',
          headers: _ajaxHeaders(_abs(url)));
      final data = jsonDecode(ep.body);
      final html = (data is Map ? data['html'] : null)?.toString() ?? '';
      final edoc = Document(html);
      for (final a in _qa(edoc, 'a.ssl-item, a.ep-item')) {
        final epId = a.attr('data-id') ?? '';
        if (epId.isEmpty) continue;
        final num = a.attr('data-number') ?? '';
        final title = ((a.attr('title')) ?? a.text).trim();
        final c = MChapter();
        c.name = num.isNotEmpty ? 'Ep $num - $title' : title;
        c.url = '${_abs(url)}?ep=$epId';
        episodes.add(c);
      }
    } catch (_) {}
    m.chapters = episodes;
    m.link = _abs(url);
    return m;
  }

  @override
  Future<List<MVideo>> getVideoList(String url) async {
    final epId = Uri.parse(_abs(url)).queryParameters['ep'] ?? '';
    if (epId.isEmpty) return <MVideo>[];
    final videos = <MVideo>[];
    try {
      final serversRes = await client.get(
          '$baseUrl/ajax/v2/episode/servers?episodeId=$epId',
          headers: _ajaxHeaders(_abs(url)));
      final sdata = jsonDecode(serversRes.body);
      final shtml = (sdata is Map ? sdata['html'] : null)?.toString() ?? '';
      final sdoc = Document(shtml);
      for (final srv in sdoc.select('div.server-item, a.server-item, div.item.server-item')) {
        final sid = srv.attr('data-id') ?? '';
        if (sid.isEmpty) continue;
        final type = srv.attr('data-type') ?? '';
        try {
          final srcRes = await client.get(
              '$baseUrl/ajax/v2/episode/sources?id=$sid',
              headers: _ajaxHeaders(_abs(url)));
          final src = jsonDecode(srcRes.body);
          final link = (src is Map ? src['link'] : null)?.toString() ?? '';
          if (link.isEmpty) continue;
          final label = type.isNotEmpty ? '${srv.text.trim()} ($type)' : srv.text.trim();
          videos.addAll(await megaCloudExtractor(link, label));
        } catch (_) {}
      }
    } catch (_) {}
    return videos;
  }

  @override
  List<dynamic> getFilterList() => [];

  @override
  List<dynamic> getSourcePreferences() => [];
}

__CLASS__ main(MSource source) {
  return __CLASS__(source: source);
}
''';

  // ── AnimeStream (WordPress anime theme) ───────────────────────────────────
  // Episodes from div.eplister; each server is a base64-encoded iframe in
  // select.mirror / ul.mirror, decoded and dispatched to the host extractors.
  static const String _animeStreamBody = r'''
  Future<List<MVideo>> _extract(String url) async {
    final u = url.toLowerCase();
    try {
      if (u.contains('dood') || u.contains('d0000d') || u.contains('ds2play') || u.contains('dooood')) return await doodExtractor(url, 'Doodstream');
      if (u.contains('streamwish') || u.contains('embedwish') || u.contains('mwish') || u.contains('vidhide') || u.contains('streamhide') || u.contains('filelions') || u.contains('kswplayer')) return await streamWishExtractor(url, 'StreamWish');
      if (u.contains('filemoon') || u.contains('moonplayer')) return await filemoonExtractor(url, '', '');
      if (u.contains('voe')) return await voeExtractor(url, 'Voe');
      if (u.contains('streamtape')) return await streamTapeExtractor(url, 'StreamTape');
      if (u.contains('mp4upload')) return await mp4UploadExtractor(url, null, '', '');
      if (u.contains('sibnet')) return await sibnetExtractor(url, '');
      if (u.contains('vidbom') || u.contains('vidbem') || u.contains('vidshare')) return await vidBomExtractor(url);
      if (u.contains('ok.ru') || u.contains('odnoklassniki')) return await okruExtractor(url);
      if (u.contains('yourupload')) return await yourUploadExtractor(url, null, 'YourUpload', '');
      if (u.contains('sendvid')) return await sendVidExtractor(url, null, '');
      if (u.contains('streamlare') || u.contains('slmaxed')) return await streamlareExtractor(url, '', '');
    } catch (_) {}
    return <MVideo>[];
  }

  String _iframeIn(String html) {
    final f = Document(html).selectFirst('iframe');
    return f == null ? '' : (f.attr('src') ?? '');
  }

  Future<MPages> _sParse(String body, bool paged) async {
    final doc = Document(body);
    final list = <MManga>[];
    final seen = <String>{};
    for (final el in _qa(doc, 'div.listupd article.bs, div.listupd div.bsx, div.bs')) {
      final a = el.selectFirst('a');
      if (a == null) continue;
      final href = a.attr('href') ?? '';
      if (href.isEmpty || seen.contains(href)) continue;
      seen.add(href);
      final img = _q1(el, 'img');
      var name = _q1(el, 'div.tt, div.ttl')?.text.trim() ?? '';
      if (name.isEmpty) name = ((a.attr('title')) ?? (img?.attr('alt')) ?? a.text).trim();
      if (name.isEmpty) continue;
      final m = MManga();
      m.name = name;
      m.link = _abs(href);
      m.imageUrl = _img(img);
      list.add(m);
    }
    return MPages(list, paged && list.isNotEmpty);
  }

  @override
  Future<MPages> getPopular(int page) async {
    final res = await client.get(
        baseUrl + '__POPULAR_PATH__'.replaceAll('{page}', '$page'),
        headers: _headers());
    return _sParse(res.body, true);
  }

  @override
  Future<MPages> getLatestUpdates(int page) async {
    final res = await client.get(
        baseUrl + '__LATEST_PATH__'.replaceAll('{page}', '$page'),
        headers: _headers());
    return _sParse(res.body, true);
  }

  @override
  Future<MPages> search(String query, int page, FilterList filterList) async {
    final res = await client.get(
        '$baseUrl/page/$page/?s=${Uri.encodeComponent(query)}',
        headers: _headers());
    return _sParse(res.body, false);
  }

  @override
  Future<MManga> getDetail(String url) async {
    final res = await client.get(_abs(url), headers: _headers());
    final doc = Document(res.body);
    final m = MManga();
    m.name = _q1(doc, 'h1.entry-title, div.infox h1, .entry-title')?.text.trim() ?? '';
    m.imageUrl = _img(_q1(doc, 'div.thumb img, div.bigcontent img, .thumbook img'));
    m.description = _q1(doc, 'div.entry-content, div.desc, .synp .entry-content')?.text.trim() ?? '';
    final genre = <String>[];
    for (final g in _qa(doc, 'div.genxed a, .genre-info a, span.mgen a')) {
      final t = g.text.trim();
      if (t.isNotEmpty) genre.add(t);
    }
    if (genre.isNotEmpty) m.genre = genre;
    final episodes = <MChapter>[];
    for (final a in _qa(doc, 'div.eplister > ul > li > a, div.eplister ul li a')) {
      final href = a.attr('href') ?? '';
      if (href.isEmpty) continue;
      final num = _q1(a, '.epl-num')?.text.trim() ?? '';
      final t = _q1(a, '.epl-title')?.text.trim() ?? a.text.trim();
      final c = MChapter();
      c.name = num.isNotEmpty ? '$num - $t' : t;
      c.url = _abs(href);
      episodes.add(c);
    }
    m.chapters = episodes;
    m.link = _abs(url);
    return m;
  }

  @override
  Future<List<MVideo>> getVideoList(String url) async {
    final res = await client.get(_abs(url), headers: _headers());
    final doc = Document(res.body);
    final videos = <MVideo>[];
    final embeds = <String>{};
    final def = _q1(doc, 'div#pembed iframe, div.player-embed iframe, iframe[src]');
    if (def != null) {
      final s = def.attr('src') ?? '';
      if (s.isNotEmpty) embeds.add(_abs(s));
    }
    for (final opt in doc.select('select.mirror > option[data-index], ul.mirror a[data-em]')) {
      var enc = opt.attr('value') ?? '';
      if (enc.isEmpty) enc = opt.attr('data-em') ?? '';
      if (enc.isEmpty) continue;
      try {
        final html = utf8.decode(base64.decode(enc));
        final s = _iframeIn(html);
        if (s.isNotEmpty) embeds.add(_abs(s));
      } catch (_) {}
    }
    for (final e in embeds) {
      videos.addAll(await _extract(e));
    }
    return videos;
  }

  @override
  List<dynamic> getFilterList() => [];

  @override
  List<dynamic> getSourcePreferences() => [];
}

__CLASS__ main(MSource source) {
  return __CLASS__(source: source);
}
''';

  // ── MangaThemesia / WPMangaStream (Asura / Flame family) ──────────────────
  // Ported from the JS body. The part the generic body lacks: reader pages come
  // from a "images":[...] JSON blob (ts_reader), with an #readerarea <img>
  // fallback. Serves manga AND novel (LightNovel-WP) sites.
  static const String _mangaThemesiaBody = r'''
  Future<MPages> _tsList(String body) async {
    final doc = Document(body);
    final list = <MManga>[];
    final seen = <String>{};
    for (final el in _qa(doc, '__ITEM_SEL__')) {
      final a = el.selectFirst('a');
      if (a == null) continue;
      final link = _abs(a.attr('href'));
      if (link.isEmpty || seen.contains(link)) continue;
      seen.add(link);
      var name = (a.attr('title') ?? '').trim();
      if (name.isEmpty) name = _q1(el, 'div.tt, .tt')?.text.trim() ?? '';
      if (name.isEmpty) name = a.text.trim();
      final m = MManga();
      m.name = name;
      m.link = link;
      m.imageUrl = _img(el.selectFirst('img'));
      list.add(m);
    }
    return MPages(list, list.isNotEmpty);
  }

  @override
  Future<MPages> getPopular(int page) async {
    final res = await client.get(
        baseUrl + '__POPULAR_PATH__'.replaceAll('{page}', '$page'),
        headers: _headers());
    return _tsList(res.body);
  }

  @override
  Future<MPages> getLatestUpdates(int page) async {
    final res = await client.get(
        baseUrl + '__LATEST_PATH__'.replaceAll('{page}', '$page'),
        headers: _headers());
    return _tsList(res.body);
  }

  @override
  Future<MPages> search(String query, int page, FilterList filterList) async {
    final res = await client.get(
        '$baseUrl/page/$page/?s=${Uri.encodeComponent(query)}',
        headers: _headers());
    return _tsList(res.body);
  }

  @override
  Future<MManga> getDetail(String url) async {
    final res = await client.get(_abs(url), headers: _headers());
    final doc = Document(res.body);
    final m = MManga();
    m.name = _q1(doc, 'h1.entry-title, .entry-title')?.text.trim() ?? '';
    m.imageUrl = _img(_q1(doc, 'div.thumb img, .thumb img'));
    m.description = _q1(doc, 'div.entry-content, .desc')?.text.trim() ?? '';
    final genre = <String>[];
    for (final g in _qa(doc, 'span.mgen a, div.gnr a, .seriestugenre a')) {
      final t = g.text.trim();
      if (t.isNotEmpty) genre.add(t);
    }
    if (genre.isNotEmpty) m.genre = genre;
    final chapters = <MChapter>[];
    for (final el in _qa(doc, '#chapterlist li, div.bxcl li, div.cl li, ul.clstyle li')) {
      final a = el.selectFirst('a');
      if (a == null) continue;
      var nm = _q1(el, 'span.chapternum, .lch a')?.text.trim() ?? '';
      if (nm.isEmpty) nm = a.text.trim();
      final c = MChapter();
      c.name = nm;
      c.url = _abs(a.attr('href'));
      chapters.add(c);
    }
    m.chapters = chapters;
    m.link = _abs(url);
    return m;
  }

  @override
  Future<List<dynamic>> getPageList(String url) async {
    final res = await client.get(_abs(url), headers: _headers());
    final body = res.body;
    final pages = <String>[];
    final match = RegExp(r'"images"\s*:\s*(\[[\s\S]*?\])').firstMatch(body);
    if (match != null) {
      try {
        final arr = jsonDecode(match.group(1) ?? '[]') as List;
        for (final s in arr) {
          final str = s.toString();
          if (str.isNotEmpty) pages.add(_abs(str.replaceAll('\\/', '/')));
        }
      } catch (_) {}
    }
    if (pages.isEmpty) {
      final doc = Document(body);
      for (final img in _qa(doc, '#readerarea img, div.reading-content img, .rdminimal img')) {
        final src = (img.attr('data-src') ?? img.attr('data-lazy-src') ?? img.getSrc() ?? '').trim();
        if (src.isNotEmpty && !src.startsWith('data:')) pages.add(_abs(src));
      }
    }
    return pages;
  }

  @override
  Future<String> getHtmlContent(String url) async {
    final res = await client.get(_abs(url), headers: _headers());
    final doc = Document(res.body);
    final el = _q1(doc, '#readerarea, .epcontent, .entry-content, div.text-left, div.reading-content, .chapter-content');
    return el == null ? '' : el.innerHtml;
  }

  @override
  List<dynamic> getFilterList() => [];

  @override
  List<dynamic> getSourcePreferences() => [];
}

__CLASS__ main(MSource source) {
  return __CLASS__(source: source);
}
''';

  // ── MMRCMS (My Manga Reader CMS) ──────────────────────────────────────────
  // Ported from the JS body: /filterList browse, /search JSON suggestions, and
  // pages from #arraydata (a comma-separated URL list) with an <img> fallback.
  static const String _mmrcmsBody = r'''
  Future<MPages> _list(String path, int page) async {
    final res = await client.get(
        _abs(path.replaceAll('{page}', '$page')), headers: _headers());
    final doc = Document(res.body);
    final list = <MManga>[];
    for (final el in _qa(doc, '.media, .manga-item, .col-sm-6')) {
      final a = _q1(el, "a.chart-title, .caption h3 a, a.manga-title, h3 a, a[href*='/manga/']");
      if (a == null) continue;
      final href = a.attr('href') ?? '';
      final name = a.text.trim();
      if (href.isEmpty || name.isEmpty) continue;
      final m = MManga();
      m.name = name;
      m.link = _abs(href);
      m.imageUrl = _img(_q1(el, 'img'));
      list.add(m);
    }
    return MPages(list, list.length >= 10);
  }

  @override
  Future<MPages> getPopular(int page) =>
      _list('/filterList?page={page}&sortBy=views&asc=false', page);

  @override
  Future<MPages> getLatestUpdates(int page) =>
      _list('/latest-release?page={page}', page);

  @override
  Future<MPages> search(String query, int page, FilterList filterList) async {
    final res = await client.get(
        _abs('/search?query=${Uri.encodeComponent(query)}'),
        headers: _headers());
    try {
      final data = jsonDecode(res.body);
      final list = <MManga>[];
      final suggestions = data is Map ? data['suggestions'] : null;
      if (suggestions is List) {
        for (final s in suggestions) {
          final name = (s is Map ? s['value'] : null)?.toString() ?? '';
          final slug = (s is Map ? s['data'] : null)?.toString() ?? '';
          if (name.isNotEmpty && slug.isNotEmpty) {
            final m = MManga();
            m.name = name;
            m.link = _abs('/manga/$slug');
            list.add(m);
          }
        }
      }
      return MPages(list, false);
    } catch (_) {
      return _list(
          '/filterList?page={page}&sortBy=name&asc=true&alpha=${Uri.encodeComponent(query)}',
          page);
    }
  }

  @override
  Future<MManga> getDetail(String url) async {
    final res = await client.get(_abs(url), headers: _headers());
    final doc = Document(res.body);
    final m = MManga();
    m.name = _q1(doc, 'h2.widget-title, h1.widget-title, .widget-title, h1, .listmanga-header')?.text.trim() ?? '';
    m.imageUrl = _img(_q1(doc, '.boxed img, img.img-responsive, .thumbnail img'));
    m.description = _q1(doc, 'div[itemprop=description], .well p, .manga-desc, .summary')?.text.trim() ?? '';
    final authEl = _q1(doc, "a[href*='/author/'], [itemprop=author]");
    if (authEl != null) m.author = authEl.text.trim();
    final genre = <String>[];
    for (final g in _qa(doc, "a[href*='/category/'], .tag-links a, .genres a, [itemprop=genre]")) {
      final t = g.text.trim();
      if (t.isNotEmpty) genre.add(t);
    }
    if (genre.isNotEmpty) m.genre = genre;
    final chapters = <MChapter>[];
    for (final li in _qa(doc, 'ul.chapters li, .chapters li')) {
      final a = _q1(li, "h5 a, h3 a, .chapter-title-rtl a, a[href*='/manga/']");
      if (a == null) continue;
      final href = a.attr('href') ?? '';
      if (href.isEmpty) continue;
      var nm = a.text.trim();
      final em = _q1(li, 'em');
      if (em != null && em.text.trim().isNotEmpty) nm = '$nm ${em.text.trim()}'.trim();
      final c = MChapter();
      c.name = nm;
      c.url = _abs(href);
      chapters.add(c);
    }
    m.chapters = chapters;
    m.link = _abs(url);
    return m;
  }

  @override
  Future<List<dynamic>> getPageList(String url) async {
    final res = await client.get(_abs(url), headers: _headers());
    final doc = Document(res.body);
    final arr = _q1(doc, '#arraydata');
    if (arr != null && arr.text.trim().isNotEmpty) {
      return arr.text.trim().split(',')
          .map((u) => _abs(u.trim())).where((u) => u.isNotEmpty).toList();
    }
    final pages = <String>[];
    for (final img in _qa(doc, '#all img, .viewer img, img.img-responsive')) {
      final src = img.getSrc();
      if (src != null && src.isNotEmpty) pages.add(_abs(src));
    }
    return pages;
  }

  @override
  List<dynamic> getFilterList() => [];

  @override
  List<dynamic> getSourcePreferences() => [];
}

__CLASS__ main(MSource source) {
  return __CLASS__(source: source);
}
''';
}
