import 'mangayomi_js_generator.dart';

/// Emits a **Dart** source for RepoForge, in the same shape as a hand-written
/// Foxtensions extension (`class DefaultExtension extends MProvider`).
///
/// Why Dart and not the JS this replaces: `d4rt` is one interpreter on every
/// platform, whereas `flutter_js` is QuickJS on Android and JavaScriptCore on
/// iOS. Worse, the JS HTTP bridge returns a response whose `body` never reaches
/// the source — verified by running a generated JS source against the live site,
/// where the fetch reported no body at all and every selector therefore matched
/// nothing. That made *every* generated JS source non-functional on both
/// platforms. The Dart runtime is the one the app defaults to in
/// `lib/eval/lib.dart`, and it is what every working Foxtensions source uses.
///
/// All detection work is reused as-is: framework identification, the selector
/// catalog and endpoint discovery all come from [MangayomiJsGenerator]'s spec
/// parsing, so only the code-emission layer differs.
class MangayomiDartGenerator {
  /// The generated `.dart` source text, ready to run under d4rt.
  static String generateSource(Map<String, dynamic> ext) {
    final s = MangayomiJsGenerator.specView(ext);

    final String body;
    if (s.itemType == 2) {
      body = _novelBody;
    } else if (s.itemType == 1) {
      body = _animeBody;
    } else {
      body = _mangaBody;
    }

    return _fill(_header + body, s);
  }

  /// Repo-relative path for the generated file, e.g. `manga/src/en/foo.dart`.
  static String pkgPath(Map<String, dynamic> ext) =>
      MangayomiJsGenerator.pkgPath(ext).replaceAll(RegExp(r'\.js$'), '.dart');

  static String _fill(String template, DartSpecView s) {
    final map = <String, String>{
      '__CLASS__': s.className,
      '__POPULAR_PATH__': _d(s.popularPath),
      '__LATEST_PATH__': _d(s.latestPath),
      '__SEARCH_PATH__': _d(s.searchPath),
      '__ITEM_SEL__': _d(s.item),
      '__TITLE_SEL__': _d(s.title),
      '__COVER_SEL__': _d(s.cover),
      '__COVER_ATTR__': _d(s.coverAttr),
      '__NEXT_SEL__': _d(s.nextPage),
      '__D_TITLE__': _d(s.detailTitle),
      '__D_COVER__': _d(s.detailCover),
      '__D_DESC__': _d(s.detailDesc),
      '__D_AUTHOR__': _d(s.detailAuthor),
      '__D_GENRE__': _d(s.detailGenre),
      '__CH_LIST__': _d(s.chapterList),
      '__CH_NAME__': _d(s.chapterName),
      '__PAGE_IMG__': _d(s.pageImages),
      '__PAGE_ATTR__': _d(s.pageImageAttr),
      '__EP_LIST__': _d(s.episodeList),
      '__NAME__': _d(s.name),
    };
    var out = template;
    map.forEach((k, v) => out = out.replaceAll(k, v));
    return out;
  }

  /// Escape for a Dart single-quoted string literal.
  static String _d(String s) =>
      s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$');

  // ── Shared preamble ──────────────────────────────────────────────────────
  static const String _header = r'''
// Generated by RepoForge. Runs on d4rt, the same runtime as hand-written
// Foxtensions sources.

import 'package:foxlations/bridge_lib.dart';

class __CLASS__ extends MProvider {
  __CLASS__({required this.source});

  MSource source;
  final Client client = Client();

  String get baseUrl => source.baseUrl;

  Map<String, String> _headers() => {'Referer': '$baseUrl/'};

  String _abs(String? url) {
    if (url == null || url.isEmpty) return '';
    if (url.startsWith('http')) return url;
    if (url.startsWith('//')) return 'https:$url';
    return '$baseUrl${url.startsWith('/') ? url : '/$url'}';
  }

  /// A role's selector is a comma-separated candidate list (the framework's own
  /// selectors first, then generic fallbacks). Try each in turn and keep the
  /// first that matches, so one source copes with a site changing its markup
  /// or serving a different layout on its search page than its browse page.
  List<MElement> _qa(dynamic node, String csv) {
    for (final s in csv.split(',')) {
      final t = s.trim();
      if (t.isEmpty) continue;
      try {
        final e = node.select(t);
        if (e != null && e.isNotEmpty) return e;
      } catch (_) {}
    }
    return <MElement>[];
  }

  MElement? _q1(dynamic node, String csv) {
    for (final s in csv.split(',')) {
      final t = s.trim();
      if (t.isEmpty) continue;
      try {
        final e = node.selectFirst(t);
        if (e != null) return e;
      } catch (_) {}
    }
    return null;
  }

  /// Covers are usually lazy-loaded and sites disagree on which attribute holds
  /// the real address, so try the common set and skip inline placeholders.
  String _img(MElement? el) {
    if (el == null) return '';
    for (final a in ['__COVER_ATTR__', 'data-src', 'data-lazy-src',
                     'data-original', 'data-url', 'data-image']) {
      if (a.isEmpty) continue;
      final v = el.attr(a);
      if (v != null && v.isNotEmpty && !v.startsWith('data:')) return _abs(v);
    }
    final ss = el.attr('srcset');
    if (ss != null && ss.isNotEmpty) {
      final first = ss.split(',').first.trim().split(' ').first;
      if (first.isNotEmpty && !first.startsWith('data:')) return _abs(first);
    }
    final s = el.getSrc();
    if (s != null && s.isNotEmpty && !s.startsWith('data:')) return _abs(s);
    return '';
  }

  /// Name, most reliable first: the title element's text, its title attribute
  /// (cover-only anchors carry the name there), then the cover's alt text.
  String _name(MElement item, MElement? titleEl, MElement? img) {
    var n = titleEl == null ? '' : titleEl.text.trim();
    if (n.isEmpty && titleEl != null) n = (titleEl.attr('title') ?? '').trim();
    if (n.isEmpty && img != null) n = (img.attr('alt') ?? '').trim();
    if (n.isEmpty) {
      final a = item.selectFirst('a');
      if (a != null) n = a.text.trim();
    }
    return n;
  }

  String _href(MElement item, MElement? titleEl) {
    final fromTitle = titleEl?.attr('href');
    if (fromTitle != null && fromTitle.isNotEmpty) return fromTitle;
    // The card may itself BE the anchor rather than contain one — common where
    // the whole tile is clickable. Looking only for a descendant <a> found
    // nothing and silently dropped every result.
    final own = item.attr('href');
    if (own != null && own.isNotEmpty) return own;
    return item.selectFirst('a')?.attr('href') ?? '';
  }
''';

  // ── Manga ────────────────────────────────────────────────────────────────
  static const String _mangaBody = r'''
  Future<MPages> _list(String pathTemplate, int page) async {
    final url = baseUrl + pathTemplate.replaceAll('{page}', '$page');
    final res = await client.get(url, headers: _headers());
    final doc = Document(res.body);
    final list = <MManga>[];

    for (final el in _qa(doc, '__ITEM_SEL__')) {
      final titleEl = _q1(el, '__TITLE_SEL__');
      final img = _q1(el, '__COVER_SEL__');
      final name = _name(el, titleEl, img);
      final href = _href(el, titleEl);
      // Require both. Ad slots dropped into a results grid match the card
      // selector but supply only one, which is how an advert gets listed.
      if (name.isEmpty || href.isEmpty) continue;
      final m = MManga();
      m.name = name;
      m.link = _abs(href);
      m.imageUrl = _img(img);
      list.add(m);
    }

    final hasNext = '__NEXT_SEL__'.isNotEmpty
        ? _q1(doc, '__NEXT_SEL__') != null
        : list.isNotEmpty;
    return MPages(list, hasNext);
  }

  @override
  Future<MPages> getPopular(int page) => _list('__POPULAR_PATH__', page);

  @override
  Future<MPages> getLatestUpdates(int page) => _list('__LATEST_PATH__', page);

  @override
  Future<MPages> search(String query, int page, FilterList filterList) {
    final p = '__SEARCH_PATH__'
        .replaceAll('{query}', Uri.encodeComponent(query));
    return _list(p, page);
  }

  /// OpenGraph is near-universal on content sites, so it fills the gaps when a
  /// bespoke site matches none of the detected selectors.
  String _meta(Document doc, List<String> props) {
    for (final p in props) {
      final el = doc.selectFirst("meta[property='" + p + "']") ??
          doc.selectFirst("meta[name='" + p + "']");
      final c = el?.attr('content');
      if (c != null && c.trim().isNotEmpty) return c.trim();
    }
    return '';
  }

  @override
  Future<MManga> getDetail(String url) async {
    final res = await client.get(_abs(url), headers: _headers());
    final doc = Document(res.body);
    final m = MManga();

    var name = _q1(doc, '__D_TITLE__')?.text.trim() ?? '';
    if (name.isEmpty) name = _meta(doc, ['og:title', 'twitter:title']);
    if (name.isEmpty) name = doc.selectFirst('h1')?.text.trim() ?? '';
    m.name = name;

    // Prefer og:image: the generic cover selector often grabs a site logo.
    var cover = _meta(doc, ['og:image', 'twitter:image']);
    if (cover.isEmpty) cover = _img(_q1(doc, '__D_COVER__'));
    m.imageUrl = _abs(cover);

    var desc = _q1(doc, '__D_DESC__')?.text.trim() ?? '';
    if (desc.isEmpty) desc = _meta(doc, ['og:description', 'description']);
    m.description = desc;

    final author = _q1(doc, '__D_AUTHOR__');
    if (author != null) m.author = author.text.trim();

    final genres = <String>[];
    for (final g in _qa(doc, '__D_GENRE__')) {
      final t = g.text.trim();
      if (t.isNotEmpty && t.length < 30 && !genres.contains(t)) genres.add(t);
    }
    if (genres.isNotEmpty) m.genre = genres;

    final chapters = <MChapter>[];
    for (final el in _qa(doc, '__CH_LIST__')) {
      final a = _q1(el, '__CH_NAME__') ?? el.selectFirst('a');
      if (a == null) continue;
      final href = a.attr('href') ?? el.attr('href') ?? '';
      if (href.isEmpty) continue;
      final c = MChapter();
      c.url = _abs(href);
      c.name = a.text.trim();
      chapters.add(c);
    }
    m.chapters = chapters;
    m.link = _abs(url);
    return m;
  }

  @override
  Future<List<dynamic>> getPageList(String url) async {
    final res = await client.get(_abs(url), headers: _headers());
    final doc = Document(res.body);
    final pages = <String>[];
    for (final img in _qa(doc, '__PAGE_IMG__')) {
      final v = img.attr('__PAGE_ATTR__') ?? img.getSrc();
      if (v != null && v.isNotEmpty && !v.startsWith('data:')) {
        pages.add(_abs(v));
      }
    }
    return pages;
  }

  @override
  List<dynamic> getFilterList() => [];

  @override
  List<dynamic> getSourcePreferences() => [];
}

__CLASS__ main(MSource source) {
  return __CLASS__(source: source);
}
''';

  // ── Light novel: chapters are text, not page images ──────────────────────
  static const String _novelBody = r'''
  Future<MPages> _list(String pathTemplate, int page) async {
    final url = baseUrl + pathTemplate.replaceAll('{page}', '$page');
    final res = await client.get(url, headers: _headers());
    final doc = Document(res.body);
    final list = <MManga>[];

    for (final el in _qa(doc, '__ITEM_SEL__')) {
      final titleEl = _q1(el, '__TITLE_SEL__');
      final img = _q1(el, '__COVER_SEL__');
      final name = _name(el, titleEl, img);
      final href = _href(el, titleEl);
      if (name.isEmpty || href.isEmpty) continue;
      final m = MManga();
      m.name = name;
      m.link = _abs(href);
      m.imageUrl = _img(img);
      list.add(m);
    }

    final hasNext = '__NEXT_SEL__'.isNotEmpty
        ? _q1(doc, '__NEXT_SEL__') != null
        : list.isNotEmpty;
    return MPages(list, hasNext);
  }

  @override
  Future<MPages> getPopular(int page) => _list('__POPULAR_PATH__', page);

  @override
  Future<MPages> getLatestUpdates(int page) => _list('__LATEST_PATH__', page);

  @override
  Future<MPages> search(String query, int page, FilterList filterList) {
    final p = '__SEARCH_PATH__'
        .replaceAll('{query}', Uri.encodeComponent(query));
    return _list(p, page);
  }

  @override
  Future<MManga> getDetail(String url) async {
    final res = await client.get(_abs(url), headers: _headers());
    final doc = Document(res.body);
    final m = MManga();

    var name = _q1(doc, '__D_TITLE__')?.text.trim() ?? '';
    if (name.isEmpty) name = doc.selectFirst('h1')?.text.trim() ?? '';
    m.name = name;

    final coverEl = _q1(doc, '__D_COVER__');
    if (coverEl != null) m.imageUrl = _img(coverEl);

    final desc = _q1(doc, '__D_DESC__');
    if (desc != null) m.description = desc.text.trim();

    final author = _q1(doc, '__D_AUTHOR__');
    if (author != null) m.author = author.text.trim();

    final chapters = <MChapter>[];
    for (final el in _qa(doc, '__CH_LIST__')) {
      final a = _q1(el, '__CH_NAME__') ?? el.selectFirst('a');
      if (a == null) continue;
      final href = a.attr('href') ?? el.attr('href') ?? '';
      if (href.isEmpty) continue;
      final c = MChapter();
      c.url = _abs(href);
      c.name = a.text.trim();
      chapters.add(c);
    }
    m.chapters = chapters;
    m.link = _abs(url);
    return m;
  }

  /// Novels deliver the chapter body as HTML text rather than page images.
  @override
  Future<String> getHtmlContent(String url) async {
    final res = await client.get(_abs(url), headers: _headers());
    final doc = Document(res.body);
    final el = _q1(doc, '__PAGE_IMG__');
    return el == null ? '' : el.innerHtml;
  }

  @override
  List<dynamic> getFilterList() => [];

  @override
  List<dynamic> getSourcePreferences() => [];
}

__CLASS__ main(MSource source) {
  return __CLASS__(source: source);
}
''';

  // ── Anime: episodes instead of chapters ──────────────────────────────────
  static const String _animeBody = r'''
  Future<MPages> _list(String pathTemplate, int page) async {
    final url = baseUrl + pathTemplate.replaceAll('{page}', '$page');
    final res = await client.get(url, headers: _headers());
    final doc = Document(res.body);
    final list = <MManga>[];

    for (final el in _qa(doc, '__ITEM_SEL__')) {
      final titleEl = _q1(el, '__TITLE_SEL__');
      final img = _q1(el, '__COVER_SEL__');
      final name = _name(el, titleEl, img);
      final href = _href(el, titleEl);
      if (name.isEmpty || href.isEmpty) continue;
      final m = MManga();
      m.name = name;
      m.link = _abs(href);
      m.imageUrl = _img(img);
      list.add(m);
    }

    final hasNext = '__NEXT_SEL__'.isNotEmpty
        ? _q1(doc, '__NEXT_SEL__') != null
        : list.isNotEmpty;
    return MPages(list, hasNext);
  }

  @override
  Future<MPages> getPopular(int page) => _list('__POPULAR_PATH__', page);

  @override
  Future<MPages> getLatestUpdates(int page) => _list('__LATEST_PATH__', page);

  @override
  Future<MPages> search(String query, int page, FilterList filterList) {
    final p = '__SEARCH_PATH__'
        .replaceAll('{query}', Uri.encodeComponent(query));
    return _list(p, page);
  }

  @override
  Future<MManga> getDetail(String url) async {
    final res = await client.get(_abs(url), headers: _headers());
    final doc = Document(res.body);
    final m = MManga();

    var name = _q1(doc, '__D_TITLE__')?.text.trim() ?? '';
    if (name.isEmpty) name = doc.selectFirst('h1')?.text.trim() ?? '';
    m.name = name;

    final coverEl = _q1(doc, '__D_COVER__');
    if (coverEl != null) m.imageUrl = _img(coverEl);

    final desc = _q1(doc, '__D_DESC__');
    if (desc != null) m.description = desc.text.trim();

    final episodes = <MChapter>[];
    for (final el in _qa(doc, '__EP_LIST__')) {
      final a = el.selectFirst('a') ?? el;
      final href = a.attr('href') ?? '';
      if (href.isEmpty) continue;
      final c = MChapter();
      c.url = _abs(href);
      c.name = a.text.trim();
      episodes.add(c);
    }
    m.chapters = episodes;
    m.link = _abs(url);
    return m;
  }

  /// Episode pages nearly always delegate playback to a third-party host in an
  /// iframe, and each host needs its own extractor. Generation can't know which
  /// one a site uses, so the embed is surfaced as-is rather than guessed at.
  @override
  Future<List<MVideo>> getVideoList(String url) async {
    final res = await client.get(_abs(url), headers: _headers());
    final doc = Document(res.body);
    final videos = <MVideo>[];
    for (final f in doc.select('iframe')) {
      final src = f.attr('src');
      if (src == null || src.isEmpty || src.startsWith('javascript')) continue;
      final v = MVideo();
      v.url = _abs(src);
      v.originalUrl = _abs(src);
      v.quality = 'Embed';
      v.headers = {'Referer': '$baseUrl/'};
      videos.add(v);
    }
    return videos;
  }

  @override
  List<dynamic> getFilterList() => [];

  @override
  List<dynamic> getSourcePreferences() => [];
}

__CLASS__ main(MSource source) {
  return __CLASS__(source: source);
}
''';
}
